# TODO (J1) : déclarer vos VMs Multipass dans le groupe [web]
# Récupérer les IP avec : multipass list

[web]
# taskflow-web1 ansible_host=<IP>
# taskflow-web2 ansible_host=<IP>

[web:vars]
ansible_user=ubuntu
# ansible_ssh_private_key_file=~/.ssh/taskflow_lab

[k8s_control]
localhost ansible_connection=local
